export const data = {
  kind: 'youtube#videoListResponse',
  etag: 'tX2TH_kQO0Qe1b6-kwl_giBmLOA',
  items: [
    {
      kind: 'youtube#video',
      etag: 'hp4YPNkmv5jVAda4JJWCdIsqBOM',
      id: 'mLxd2eU9L8o',
      snippet: {
        publishedAt: '2020-10-17T10:45:03Z',
        channelId: 'UCx6jsZ02B4K3SECUrkgPyzg',
        title:
          '(Eng sub) [환불원정대] 환불원정대 쇼! 음악중심 데뷔 무대! (Hangout with Yoo - refund sisters)',
        description:
          "★★★More 'Hangout with Yoo' clips are available★★★\n\niMBC\nhttp://www.imbc.com/broad/tv/ent/hangoutwithyoo/vod/\n\nWAVVE\nhttps://www.wavve.com/player/vod?programid=M_1004711100000100000&page=1",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/mLxd2eU9L8o/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/mLxd2eU9L8o/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/mLxd2eU9L8o/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/mLxd2eU9L8o/sddefault.jpg',
            width: 640,
            height: 480,
          },
        },
        channelTitle: '놀면 뭐하니?',
        tags: [
          '유재석',
          '김태호',
          '무한도전',
          '유플래시',
          '유산슬',
          '뽕포유',
          '라섹',
          '유르페우스',
          '놀면 뭐하니',
          '놀뭐',
          '무도',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title:
            '(Eng sub) [환불원정대] 환불원정대 쇼! 음악중심 데뷔 무대! (Hangout with Yoo - refund sisters)',
          description:
            "★★★More 'Hangout with Yoo' clips are available★★★\n\niMBC\nhttp://www.imbc.com/broad/tv/ent/hangoutwithyoo/vod/\n\nWAVVE\nhttps://www.wavve.com/player/vod?programid=M_1004711100000100000&page=1",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'TBNlINDmXTknVv5v2lxh-AjQt9c',
      id: 'GrDYOl1v68M',
      snippet: {
        publishedAt: '2020-10-19T09:21:05Z',
        channelId: 'UCcOYEm78CpaZQvPE6LtoSeA',
        title:
          "[런닝맨] 레전드 '3년 만의 완전체 출격! 레전드 찍은 블랙핑크' / 'RunningMan' BlackPink Special | SBS NOW",
        description:
          "525회차 - '블랙핑크 in RUNNINGMAN'\n3년 만의 완전체 출격!\n레전드 찍은 👑블랙핑크👑\n\n런닝맨🏃🏻🏃🏻‍♀️🏃🏻‍♂️‬\n☞ 매주 일요일 오후 5시 본방송\n\n#런닝맨 #블랙핑크 #BlackPink\n\n▶ Subscribe NOW! SBS NOW!  https://bit.ly/2YRf9Kn\n▶ Homepage :  https://programs.sbs.co.kr/enter/runningman/\n▶ Facebook :  https://www.facebook.com/sbsnow/\n▶ Instagram : https://www.instagram.com/sbsnow_insta/",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/GrDYOl1v68M/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/GrDYOl1v68M/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/GrDYOl1v68M/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/GrDYOl1v68M/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/GrDYOl1v68M/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'SBS NOW / SBS 공식 채널',
        tags: [
          'SBS Entertainment',
          '예고',
          '유재석',
          '하하',
          '송지효',
          '김종국',
          '이광수',
          '지석진',
          '전소민',
          '양세찬',
          '런닝맨',
          'running man Preview',
          'Yoo jae suk',
          'Haha',
          'Song jihyo',
          'Kim jong kook',
          'Lee kwang soo',
          'Ji suk jin',
          'Jeon so min',
          'Yang se chan',
          '블랙핑크',
          '블랙핑크런닝맨',
          '제니',
          '지수',
          '로제',
          '리사',
          'LovesickGirls',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title:
            "[런닝맨] 레전드 '3년 만의 완전체 출격! 레전드 찍은 블랙핑크' / 'RunningMan' BlackPink Special | SBS NOW",
          description:
            "525회차 - '블랙핑크 in RUNNINGMAN'\n3년 만의 완전체 출격!\n레전드 찍은 👑블랙핑크👑\n\n런닝맨🏃🏻🏃🏻‍♀️🏃🏻‍♂️‬\n☞ 매주 일요일 오후 5시 본방송\n\n#런닝맨 #블랙핑크 #BlackPink\n\n▶ Subscribe NOW! SBS NOW!  https://bit.ly/2YRf9Kn\n▶ Homepage :  https://programs.sbs.co.kr/enter/runningman/\n▶ Facebook :  https://www.facebook.com/sbsnow/\n▶ Instagram : https://www.instagram.com/sbsnow_insta/",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'doPSAxLfVO7jJEzaOGPWn9xjVmw',
      id: 'i-VPKzYmpME',
      snippet: {
        publishedAt: '2020-10-17T13:34:39Z',
        channelId: 'UC2jHhn8GMouSKUiauOsiR3w',
        title: "[환불원정대] Don't touch me 안무영상 By AIKI",
        description:
          "환불원정대 - Don't touch me\nChoreo by AIKI (with HOOK)\n#아이키 #AIKI #DANCE #환불원정대 #놀면뭐하니 #돈터치미 #나쁜여자 #수트댄스 #국내힙합 #힙합 #방송댄스 #케이팝 \n\nInstagram : https://www.instagram.com/aiki_kr/\nTiktok : https://www.tiktok.com/@aiki_kr/\nInfo : heyin7412@naver.com",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/i-VPKzYmpME/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/i-VPKzYmpME/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/i-VPKzYmpME/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/i-VPKzYmpME/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/i-VPKzYmpME/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Aiki아이키릿',
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title: "[환불원정대] Don't touch me 안무영상 By AIKI",
          description:
            "환불원정대 - Don't touch me\nChoreo by AIKI (with HOOK)\n#아이키 #AIKI #DANCE #환불원정대 #놀면뭐하니 #돈터치미 #나쁜여자 #수트댄스 #국내힙합 #힙합 #방송댄스 #케이팝 \n\nInstagram : https://www.instagram.com/aiki_kr/\nTiktok : https://www.tiktok.com/@aiki_kr/\nInfo : heyin7412@naver.com",
        },
      },
    },
    {
      kind: 'youtube#video',
      etag: '2zcw2rp_mmN32srICV1X5AbYw-Q',
      id: 'erOUMa9vcmM',
      snippet: {
        publishedAt: '2020-10-19T07:41:31Z',
        channelId: 'UCiwQRG2sCcfjKkgxMEdJGPg',
        title:
          "[놀면 뭐하니?] 아이키의 안무로 완성된 환불원정대의 DON'T TOUCH ME💃 헤이커몬!ㅣ#엠뚜루마뚜루 #잼모아 #엠돌핀",
        description:
          '[놀면 뭐하니?] 토요일 저녁 6시 30분 방송!\n\n_\n#엠뚜루마뚜루\n#잼모아\n#엠돌핀',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/erOUMa9vcmM/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/erOUMa9vcmM/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/erOUMa9vcmM/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/erOUMa9vcmM/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/erOUMa9vcmM/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '엠뚜루마뚜루 : MBC 공식 종합 채널',
        tags: [
          '엠뚜루마뚜루',
          '잼모아',
          '엠돌핀',
          '놀면뭐하니',
          '환불원정대',
          '아이키',
          '유퀴즈온더블럭',
          '올레디',
          '이효리',
          '엄정화',
          '화사',
          '제시',
          '천옥',
          '만옥',
          '실비',
          '은비',
          '안무',
          '무대',
          '아이돌',
          'idol',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title:
            "[놀면 뭐하니?] 아이키의 안무로 완성된 환불원정대의 DON'T TOUCH ME💃 헤이커몬!ㅣ#엠뚜루마뚜루 #잼모아 #엠돌핀",
          description:
            '[놀면 뭐하니?] 토요일 저녁 6시 30분 방송!\n\n_\n#엠뚜루마뚜루\n#잼모아\n#엠돌핀',
        },
      },
    },
    {
      kind: 'youtube#video',
      etag: 'MUdYUx4HSUWX9DxXW3J_nIxi0C8',
      id: '6cRt1xoi-w4',
      snippet: {
        publishedAt: '2020-10-19T06:25:44Z',
        channelId: 'UCskIKQGpjI5sG2ZLtWLYSmw',
        title: '미스터트롯 더 무비 온라인 제작 보고회',
        description: '',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/6cRt1xoi-w4/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/6cRt1xoi-w4/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/6cRt1xoi-w4/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/6cRt1xoi-w4/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/6cRt1xoi-w4/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '미스&미스터트롯 공식계정',
        categoryId: '22',
        liveBroadcastContent: 'none',
        localized: {
          title: '미스터트롯 더 무비 온라인 제작 보고회',
          description: '',
        },
      },
    },
    {
      kind: 'youtube#video',
      etag: '1avIuRlV5vDX8NKr0jSXnSRHXjA',
      id: 'aIO4oKgmE6M',
      snippet: {
        publishedAt: '2020-10-18T23:37:08Z',
        channelId: 'UC3m0s5XAQydCtbLHc8j1Uog',
        title:
          "[에디터's 꿀잼Pick] 벌써 동생바버♥ 올망졸망 X 꽁냥꽁냥 ☆#찐건나블리☆",
        description:
          '애깅이가 애깅이를 어여뻐라 하는 세젤귀 상황ㅠ\n\n#슈돌 #슈퍼맨이돌아왔다 #건나블리',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/aIO4oKgmE6M/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/aIO4oKgmE6M/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/aIO4oKgmE6M/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/aIO4oKgmE6M/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/aIO4oKgmE6M/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'KBS 한국방송',
        tags: [
          'KBS',
          '한국방송공사',
          'mylovekbs',
          '예고',
          '티저',
          '건후',
          '나은',
          '건나블리',
          '박주호',
          '슈돌',
          '슈퍼맨이돌아왔다',
          'The Return of Superman',
          '윌벤져스',
          '윌리엄',
          '벤틀리',
          '건나파블리',
          '찐건나블리',
          '건나블리 컴백',
          '건나블리 컴백 예고',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title:
            "[에디터's 꿀잼Pick] 벌써 동생바버♥ 올망졸망 X 꽁냥꽁냥 ☆#찐건나블리☆",
          description:
            '애깅이가 애깅이를 어여뻐라 하는 세젤귀 상황ㅠ\n\n#슈돌 #슈퍼맨이돌아왔다 #건나블리',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'KPyFrZp-vrxcvzqHigCzUdS41KA',
      id: 'UB4FzllQCyc',
      snippet: {
        publishedAt: '2020-10-19T09:00:00Z',
        channelId: 'UC3IZKseVpdzPSBaWxBxundA',
        title: "SEVENTEEN (세븐틴) 'HOME;RUN' Official MV",
        description:
          "SEVENTEEN (세븐틴) 'HOME;RUN' Official MV\n\n세븐틴의 이번 앨범 ‘; [Semicolon]’은 미니 7집 ‘헹가래’를 통해 이야기한 ‘청춘’을 향한 응원의 메시지를 다시금 공유하면서 한 발짝 더 나아가 쉼 없이 달리는 청춘에게 ‘잠깐 쉬어가며 청춘의 향연을 즐기자’라는 더욱 성숙한 긍정의 메시지를 전하는 앨범이다.\n\n현 시대를 살아가며 고군분투 하고 있는 청춘들에게 잠시나마 ‘숨 고를 시간’, ‘함께 웃으며 즐길 수 있는 시간’을 문장을 잠시 끊었다가 이어서 설명을 계속할 때 쓰이는 문장 부호인 ‘Semicolon(세미콜론)’ 에 비유, 동시대 청춘으로 살아가는 “세븐틴” 그들의 공감을 전하는 메시지를 앨범에 가득 담아내어 청춘들을 어루만질 따뜻한 위로와 응원, 공감을 주는 희망의 외침을 전한다.\n\n타이틀곡 ‘HOME;RUN’은 스윙 장르 기반의 레트로한 사운드가 돋보이는 곡으로 경쾌하고 타격감 넘치는 사운드로 ‘HOME RUN’이라는 표현이 지닌 짜릿함을 표현하였고, 무한한 성장을 지닌 청춘에게 힘찬 응원과 위로의 목소리를 선사한다.\n\nSEVENTEEN’s new album ‘; [Semicolon]’ is an album where they share the encouraging message for the ‘youth’ like they did in their 7th mini album ‘Heng:garæ’ and also the positive message that ‘we should all take a break and enjoy the youth’ with the youth that are running towards their goals without any breaks.\n\n‘Semicolon,’ which is a punctuation mark used when you pause a sentence and then resume again, is used as a metaphor to portray the ‘time to take a breath’ and ‘time to laugh and enjoy together.’ “SEVENTEEN,” as the youth who are living in the same time period as the other youth who are fighting alone and struggling through their lives, uses this metaphor to convey their hopeful and empathic message through the album to comfort and cheer for the youth.\n\nThe title song ‘HOME;RUN’ is a song based on swing genre where the retro-like sound stands out, and it portrays the excitement that the phrase ‘HOME RUN’ conveys with cheerful and rhythmical sound. It conveys powerful support and comfort to the youth with limitless potentials.\n\n#SEVENTEEN #세븐틴\n#Semicolon #세미콜론\n#HOME_RUN\n\nSEVENTEEN Official Homepage : http://www.seventeen-17.com\nSEVENTEEN Official Facebook : https://www.facebook.com/seventeennews\nSEVENTEEN Official Twitter : https://twitter.com/pledis_17\nSEVENTEEN Official Instagram : http://www.instagram.com/saythename_17\nSEVENTEEN Official Fancafe : http://cafe.daum.net/pledis-17\nSEVENTEEN Official Weverse : https://www.weverse.io/seventeen\n\nⓒ Pledis Entertainment. All Rights Reserved",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/UB4FzllQCyc/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/UB4FzllQCyc/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/UB4FzllQCyc/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/UB4FzllQCyc/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/UB4FzllQCyc/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Big Hit Labels',
        tags: [
          '에스쿱스',
          '정한',
          '조슈아',
          '준',
          '호시',
          '원우',
          '우지',
          '디에잇',
          '민규',
          '도겸',
          '승관',
          '버논',
          '디노',
          'SCOUPS',
          'JEONGHAN',
          'JOSHUA',
          'JUN',
          'HOSHI',
          'WONWOO',
          'WOOZI',
          'THE 8',
          'MINGYU',
          'DK',
          'SEUNGKWAN',
          'VERNON',
          'DINO',
          '세븐틴',
          'SEVENTEEN',
          'セブチ',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title: "SEVENTEEN (세븐틴) 'HOME;RUN' Official MV",
          description:
            "SEVENTEEN (세븐틴) 'HOME;RUN' Official MV\n\n세븐틴의 이번 앨범 ‘; [Semicolon]’은 미니 7집 ‘헹가래’를 통해 이야기한 ‘청춘’을 향한 응원의 메시지를 다시금 공유하면서 한 발짝 더 나아가 쉼 없이 달리는 청춘에게 ‘잠깐 쉬어가며 청춘의 향연을 즐기자’라는 더욱 성숙한 긍정의 메시지를 전하는 앨범이다.\n\n현 시대를 살아가며 고군분투 하고 있는 청춘들에게 잠시나마 ‘숨 고를 시간’, ‘함께 웃으며 즐길 수 있는 시간’을 문장을 잠시 끊었다가 이어서 설명을 계속할 때 쓰이는 문장 부호인 ‘Semicolon(세미콜론)’ 에 비유, 동시대 청춘으로 살아가는 “세븐틴” 그들의 공감을 전하는 메시지를 앨범에 가득 담아내어 청춘들을 어루만질 따뜻한 위로와 응원, 공감을 주는 희망의 외침을 전한다.\n\n타이틀곡 ‘HOME;RUN’은 스윙 장르 기반의 레트로한 사운드가 돋보이는 곡으로 경쾌하고 타격감 넘치는 사운드로 ‘HOME RUN’이라는 표현이 지닌 짜릿함을 표현하였고, 무한한 성장을 지닌 청춘에게 힘찬 응원과 위로의 목소리를 선사한다.\n\nSEVENTEEN’s new album ‘; [Semicolon]’ is an album where they share the encouraging message for the ‘youth’ like they did in their 7th mini album ‘Heng:garæ’ and also the positive message that ‘we should all take a break and enjoy the youth’ with the youth that are running towards their goals without any breaks.\n\n‘Semicolon,’ which is a punctuation mark used when you pause a sentence and then resume again, is used as a metaphor to portray the ‘time to take a breath’ and ‘time to laugh and enjoy together.’ “SEVENTEEN,” as the youth who are living in the same time period as the other youth who are fighting alone and struggling through their lives, uses this metaphor to convey their hopeful and empathic message through the album to comfort and cheer for the youth.\n\nThe title song ‘HOME;RUN’ is a song based on swing genre where the retro-like sound stands out, and it portrays the excitement that the phrase ‘HOME RUN’ conveys with cheerful and rhythmical sound. It conveys powerful support and comfort to the youth with limitless potentials.\n\n#SEVENTEEN #세븐틴\n#Semicolon #세미콜론\n#HOME_RUN\n\nSEVENTEEN Official Homepage : http://www.seventeen-17.com\nSEVENTEEN Official Facebook : https://www.facebook.com/seventeennews\nSEVENTEEN Official Twitter : https://twitter.com/pledis_17\nSEVENTEEN Official Instagram : http://www.instagram.com/saythename_17\nSEVENTEEN Official Fancafe : http://cafe.daum.net/pledis-17\nSEVENTEEN Official Weverse : https://www.weverse.io/seventeen\n\nⓒ Pledis Entertainment. All Rights Reserved",
        },
        defaultAudioLanguage: 'en',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'jJTWyMSdEzhIrq_ytChIlH-JEJM',
      id: 'CX8GpnlTUoo',
      snippet: {
        publishedAt: '2020-10-18T01:37:05Z',
        channelId: 'UCd4FmcWIVdWAy0-Q8OJBloQ',
        title: '어몽어스 에어팟 만들기',
        description:
          '● 3D펜 사나고 샵\nhttps://smartstore.naver.com/sanago\n● 인스타그램\nhttps://www.instagram.com/sanago_kr/\n● 3D펜카페 [사나고의 3D펜 비밀기지]\nhttps://cafe.naver.com/sanago\n● Contact 광고문의\nuggnll@naver.com\n\n도면 이미지 참고 트위터 @men1_drawing\n\n각국어 번역 자막 제작 : 컨텐츠 제작의 마무리는 컨텐츠플라이! 글로벌 진출을 위한 최고의 파트너,CONTENTSFLY에서 제작되었습니다.\nhttps://www.contentsfly.com\n      \n#사나고 #3Dpen #3D펜',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/CX8GpnlTUoo/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/CX8GpnlTUoo/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/CX8GpnlTUoo/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/CX8GpnlTUoo/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/CX8GpnlTUoo/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '사나고 Sanago',
        tags: [
          '사나고',
          '3D펜',
          '3Dpen',
          '만들기',
          'making',
          '3d프린터',
          '3Dprinting',
          '어몽어스',
        ],
        categoryId: '26',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title: '어몽어스 에어팟 만들기',
          description:
            '● 3D펜 사나고 샵\nhttps://smartstore.naver.com/sanago\n● 인스타그램\nhttps://www.instagram.com/sanago_kr/\n● 3D펜카페 [사나고의 3D펜 비밀기지]\nhttps://cafe.naver.com/sanago\n● Contact 광고문의\nuggnll@naver.com\n\n도면 이미지 참고 트위터 @men1_drawing\n\n각국어 번역 자막 제작 : 컨텐츠 제작의 마무리는 컨텐츠플라이! 글로벌 진출을 위한 최고의 파트너,CONTENTSFLY에서 제작되었습니다.\nhttps://www.contentsfly.com\n      \n#사나고 #3Dpen #3D펜',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'tHE4xZ_rCXGlTDvcYZrPVxdFMg0',
      id: 'OPWwpcoqlfo',
      snippet: {
        publishedAt: '2020-10-19T09:09:10Z',
        channelId: 'UCepUWUpH45hRTi-QePdq1Bg',
        title: '[SMTM9]  🎉 1차 예선 합격자 모음 🎉',
        description:
          'SMTM9 1차 예선 합격자 모음(EP.1)\n\n365lit, 가오가이, 노아주다, 디아크, 리비도, 릴보이, 맥대디, 맥키드, 머쉬베놈, 바이스벌사, 스카이민혁, 안병웅, 야누, 에이체스, 오왼, 원슈타인, 이로한, 전현재, 주피터, 차메인, 창빈, 칠린호미, 쿤디판다 \n\nSMTM9 매주 금요일 밤 11시 Mnet! \n#SMTM9 #쇼미더머니9 #ShowMeTheMoney9',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/OPWwpcoqlfo/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/OPWwpcoqlfo/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/OPWwpcoqlfo/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/OPWwpcoqlfo/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/OPWwpcoqlfo/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Mnet Official',
        tags: [
          'Kpop',
          'MCD',
          'mcountdown',
          'mnet',
          'playmnet',
          'pop',
          'korea',
          'music',
          'asia',
          'asian',
          '365lit',
          '가오가이',
          '노아주다',
          '디아크',
          '리비도',
          '릴보이',
          '맥대디',
          '맥키드',
          '머쉬베놈',
          '바이스벌사',
          '스카이민혁',
          '안병웅',
          '야누',
          '에이체스',
          '오왼',
          '원슈타인',
          '이로한',
          '전현재',
          '주피터',
          '차메인',
          '창빈',
          '칠린호미',
          '쿤디판다',
          '쇼미',
          '쇼미9',
          '쇼미9_1차합격자',
          '쇼미9_1차합격자모음',
          '쇼미_1차합격자모음',
          '1차합격자',
          '1차합격자모음',
          '1차예선',
          '쇼미9_1차예선',
          '쇼미9_1차예선합격자',
          '쇼미_1차예선',
          '쇼미예선',
          '쇼미9_예선',
          '쇼미9_예선합격자모음',
          '쇼미9_예선합격자',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title: '[SMTM9]  🎉 1차 예선 합격자 모음 🎉',
          description:
            'SMTM9 1차 예선 합격자 모음(EP.1)\n\n365lit, 가오가이, 노아주다, 디아크, 리비도, 릴보이, 맥대디, 맥키드, 머쉬베놈, 바이스벌사, 스카이민혁, 안병웅, 야누, 에이체스, 오왼, 원슈타인, 이로한, 전현재, 주피터, 차메인, 창빈, 칠린호미, 쿤디판다 \n\nSMTM9 매주 금요일 밤 11시 Mnet! \n#SMTM9 #쇼미더머니9 #ShowMeTheMoney9',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'vuXx0Pcgd84cgIGNotKjOiU-HfU',
      id: 'Ky3gNuatOWw',
      snippet: {
        publishedAt: '2020-10-18T08:00:01Z',
        channelId: 'UCLKuglhGlMmDteQKoniENIQ',
        title:
          '비싸도 산다! 충전기 안줘도 산다! 삼성 재드래곤 가족도 쓴다는 애플과 스티브 잡스 이야기 / 14F',
        description:
          '스티브 잡스가 고등학교 선배 워즈니악과 공동창업한 애플은 전세계인의 생활을 바꿔놓았습니다.\n스티브 잡스가 애플에서 열어 온 PC와 스마트폰의 세계, 그리고 그가 평생 만난 귀인들까지.\n지금도 계속되고 있는 애플의 전설에 대해 전해드립니다.\n#애플 #스티브잡스 #소비더머니',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/Ky3gNuatOWw/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/Ky3gNuatOWw/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/Ky3gNuatOWw/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/Ky3gNuatOWw/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/Ky3gNuatOWw/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '14F 일사에프',
        tags: [
          '14f',
          '일사에프',
          '아이폰12',
          '애플주가',
          '애플워치',
          '맥세이프',
          '스티브잡스연설명언',
          '팀쿡',
          '갤럭시노트20',
          '삼성이재용아들딸',
        ],
        categoryId: '25',
        liveBroadcastContent: 'none',
        localized: {
          title:
            '비싸도 산다! 충전기 안줘도 산다! 삼성 재드래곤 가족도 쓴다는 애플과 스티브 잡스 이야기 / 14F',
          description:
            '스티브 잡스가 고등학교 선배 워즈니악과 공동창업한 애플은 전세계인의 생활을 바꿔놓았습니다.\n스티브 잡스가 애플에서 열어 온 PC와 스마트폰의 세계, 그리고 그가 평생 만난 귀인들까지.\n지금도 계속되고 있는 애플의 전설에 대해 전해드립니다.\n#애플 #스티브잡스 #소비더머니',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'URQyMWMNs5iH67oPsROFhhPS2kE',
      id: 'EGRKv64cdVo',
      snippet: {
        publishedAt: '2020-10-19T09:59:58Z',
        channelId: 'UCy1fruN1Tl636SMmyp4x48g',
        title:
          "[김은영을 만나다] '화성인' G컵녀, 9년 만의 근황... 현재 몸무게 38kg",
        description:
          "약 9년 전, '화성인 X 파일'에 출연했던 '지컵녀' 김은영 씨. 당시 수많은 화제를 불러일으켰던 인물이죠.\n수줍고 의기소침한 모습으로 방송에 등장, 사연을 전해 관심을 받기도 했습니다.\n9년 만에 김은영 씨를 만났습니다.\n갑작스러운 아버지의 병환으로 집안이 흔들렸고, 이에 동생과 함께 '화성인 X-파일'에 출연하게 됐던 사연부터,\n몸무게 미달로 수술이 어려워 동생이 대신 간이식을 해야했던 당시의 안타까운 심경도 전했습니다.\n가족이 행복하게 사는 것이 인생의 목표라는, '화성인 지컵녀' 김은영 님의 근황입니다.",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/EGRKv64cdVo/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/EGRKv64cdVo/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/EGRKv64cdVo/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/EGRKv64cdVo/sddefault.jpg',
            width: 640,
            height: 480,
          },
        },
        channelTitle: '근황올림픽',
        tags: ['근황', '근황올림픽', '김은영', '화성인', 'G컵녀', '지컵녀'],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title:
            "[김은영을 만나다] '화성인' G컵녀, 9년 만의 근황... 현재 몸무게 38kg",
          description:
            "약 9년 전, '화성인 X 파일'에 출연했던 '지컵녀' 김은영 씨. 당시 수많은 화제를 불러일으켰던 인물이죠.\n수줍고 의기소침한 모습으로 방송에 등장, 사연을 전해 관심을 받기도 했습니다.\n9년 만에 김은영 씨를 만났습니다.\n갑작스러운 아버지의 병환으로 집안이 흔들렸고, 이에 동생과 함께 '화성인 X-파일'에 출연하게 됐던 사연부터,\n몸무게 미달로 수술이 어려워 동생이 대신 간이식을 해야했던 당시의 안타까운 심경도 전했습니다.\n가족이 행복하게 사는 것이 인생의 목표라는, '화성인 지컵녀' 김은영 님의 근황입니다.",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: '9le6jZMC9Qet60oQgLlW-VRrFyU',
      id: 'dKTs-ZfY6kI',
      snippet: {
        publishedAt: '2020-10-18T22:00:04Z',
        channelId: 'UCuFGPhfJlIngZaC2BjLaJdQ',
        title: '이런 사람은 고구마 먹지 마세요! 건강 간식 고구마의 함정!',
        description:
          '건강에 좋다는 고구마 챙겨드시는 분들이 많습니다. 그런데 고구마는 어떻게, 얼마나 드시느냐에 따라 변수가 많은 음식입니다. 자세히 설명해드릴게요!\n▶ 좀 더 알고 싶다면? 고구마의 이점 https://www.youtube.com/watch?v=qMHG7aWCtDA\n---------------------------------------------------------------------------------\n▶ 김소형 채널H 블로그 https://blog.naver.com/channel__h\n▶ 김소형 채널H 포스트 https://post.naver.com/channel__h\n▶ 김소형 채널H 인스타그램 https://www.instagram.com/oldmiko_dr.sh_/\n---------------------------------------------------------------------------------\n[알립니다]\n1. 공공의 건강 정보를 나누는 공간이므로 개인적인 건강 및 질환 상담, 약물, 제품 추천 등 일부 질문에는 답변 드릴 수 없음을 양해해 주시기 바랍니다.\n2. 진료 도중 틈틈이 답변을 작성하고 있습니다만, 모든 질문에 답변을 드리지 못해 안타깝습니다. 좀 오래 걸리더라도 답변해드릴 수 있는 항목에 대해서는 최대한 답변해드리려고 합니다.\n3. 채널H를 사랑해주시는 많은 분들을 위해 욕설, 분란을 일으킬 수 있거나 선정적인 글 등 불쾌감을 유발하는 댓글은 삭제될 수 있습니다.\n\n* 채널H의 영상은 객관적 건강 정보와 관련 연구 결과를 토대로 기획, 제작되었으므로 보시는 분의 연령, 체질, 가족력, 기왕력 등 개인적 특성에 따라 정보의 적용이 달라질 수 있습니다. 개인에게 적용되는 구체적 정보는 건강 상태를 잘 알고 있는 주치의, 전문가와 상담으로 얻으실 수 있습니다.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/dKTs-ZfY6kI/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/dKTs-ZfY6kI/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/dKTs-ZfY6kI/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/dKTs-ZfY6kI/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/dKTs-ZfY6kI/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '김소형 채널H',
        tags: [
          '김소형',
          '김소형원장',
          '한의학',
          '한방차',
          '한방',
          '본초',
          '한의사',
          '김소형한의사',
          '동의보감',
          '채널H',
          'chh',
          '고구마h',
          '당뇨h',
          '혈당h',
        ],
        categoryId: '26',
        liveBroadcastContent: 'none',
        localized: {
          title: '이런 사람은 고구마 먹지 마세요! 건강 간식 고구마의 함정!',
          description:
            '건강에 좋다는 고구마 챙겨드시는 분들이 많습니다. 그런데 고구마는 어떻게, 얼마나 드시느냐에 따라 변수가 많은 음식입니다. 자세히 설명해드릴게요!\n▶ 좀 더 알고 싶다면? 고구마의 이점 https://www.youtube.com/watch?v=qMHG7aWCtDA\n---------------------------------------------------------------------------------\n▶ 김소형 채널H 블로그 https://blog.naver.com/channel__h\n▶ 김소형 채널H 포스트 https://post.naver.com/channel__h\n▶ 김소형 채널H 인스타그램 https://www.instagram.com/oldmiko_dr.sh_/\n---------------------------------------------------------------------------------\n[알립니다]\n1. 공공의 건강 정보를 나누는 공간이므로 개인적인 건강 및 질환 상담, 약물, 제품 추천 등 일부 질문에는 답변 드릴 수 없음을 양해해 주시기 바랍니다.\n2. 진료 도중 틈틈이 답변을 작성하고 있습니다만, 모든 질문에 답변을 드리지 못해 안타깝습니다. 좀 오래 걸리더라도 답변해드릴 수 있는 항목에 대해서는 최대한 답변해드리려고 합니다.\n3. 채널H를 사랑해주시는 많은 분들을 위해 욕설, 분란을 일으킬 수 있거나 선정적인 글 등 불쾌감을 유발하는 댓글은 삭제될 수 있습니다.\n\n* 채널H의 영상은 객관적 건강 정보와 관련 연구 결과를 토대로 기획, 제작되었으므로 보시는 분의 연령, 체질, 가족력, 기왕력 등 개인적 특성에 따라 정보의 적용이 달라질 수 있습니다. 개인에게 적용되는 구체적 정보는 건강 상태를 잘 알고 있는 주치의, 전문가와 상담으로 얻으실 수 있습니다.',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'Ekwka8mrsRIwqrOThETLsmGtpGE',
      id: 'v4no5gLquMw',
      snippet: {
        publishedAt: '2020-10-19T11:39:56Z',
        channelId: 'UCIG4gr_wIy5CIlcFciUbIQw',
        title:
          '5살 아이가 그린 그림을 미술평론가에게 가격을 매겨달라고 하면 얼마를 써줄까?',
        description:
          '5살 아이가 그린 그림을 미술평론가에게 가격을 매겨달라고 하면 얼마를 써줄까?\n제가 한번 실험해보았습니다\n\n협조 : 미술평론가 김진혁, 윤새해, 짤툰, 러브둥둥\n          www.artncritic.com , www.instagram.com/gkiiiim\n편집 : 이재혁\n기획 : 신연지',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/v4no5gLquMw/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/v4no5gLquMw/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/v4no5gLquMw/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/v4no5gLquMw/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/v4no5gLquMw/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '진용진',
        categoryId: '22',
        liveBroadcastContent: 'none',
        localized: {
          title:
            '5살 아이가 그린 그림을 미술평론가에게 가격을 매겨달라고 하면 얼마를 써줄까?',
          description:
            '5살 아이가 그린 그림을 미술평론가에게 가격을 매겨달라고 하면 얼마를 써줄까?\n제가 한번 실험해보았습니다\n\n협조 : 미술평론가 김진혁, 윤새해, 짤툰, 러브둥둥\n          www.artncritic.com , www.instagram.com/gkiiiim\n편집 : 이재혁\n기획 : 신연지',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'QjuCp4hejglQjJ2IJ6-_LjkII1Q',
      id: 'Y7FMbWfAFTc',
      snippet: {
        publishedAt: '2020-10-19T09:00:05Z',
        channelId: 'UCS3nrcZQBB3-WFAt0KorPfA',
        title:
          '[M/V] 임창정 - 힘든 건 사랑이 아니다 (IM CHANG JUNG - Love should not be harsh on you)',
        description:
          '[M/V] 임창정 - 힘든 건 사랑이 아니다 (IM CHANG JUNG - Love should not be harsh on you)\n\n임창정 정규 16집 타이틀 곡 "힘든 건 사랑이 아니다"는 ‘임창정 16집 타이틀 선정단’의 직접 투표를 통한 압도적인 지지로 선정되었으며 임창정 본인이 재녹음을 수없이 할 만큼 애착을 갖고 탄생시킨 곡이다. 타이틀 선정단이 노래를 듣자마자 눈물을 흘릴 만큼 애절하고 가슴 아픈 사랑 이야기를 담고 있으며 "또다시 사랑" "내가 저지른 사랑" "하루도 그대를 사랑한 적이 없었다" 이후 귓가에 꽂히게 하는 중독성 강한 곡이다. 빗소리와 함께 피아노로 시작하는 전주는 리스너들로 하여금 감성에 빠져들게 하며 임창정의 독보적인 고음으로 빚어낸 후렴의 절정은 사랑하는 사람을 떠나보낼 수밖에 없는 슬픔을 극대화한다. 오랜 시간 함께 해온 히트 메이커 콤비 ‘임창정’과 ‘멧돼지’, 그리고 신예 프로듀서 ‘늑대’ 가 함께 만들어 낸 또 다른 역작으로, 국내 최고의 세션들이 참여해 최고의 퀄리티를 만들어 냈다.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/Y7FMbWfAFTc/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/Y7FMbWfAFTc/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/Y7FMbWfAFTc/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/Y7FMbWfAFTc/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/Y7FMbWfAFTc/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'rhybeat 리빗',
        tags: [
          'K-Pop',
          'KPop',
          'K팝',
          '케이팝',
          'Korean Pop',
          'Idol',
          '아이돌',
          '음악',
          'Music',
          '가요',
          '인터파크',
          'Interpark',
          '리빗',
          'rhybeat',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        localized: {
          title:
            '[M/V] 임창정 - 힘든 건 사랑이 아니다 (IM CHANG JUNG - Love should not be harsh on you)',
          description:
            '[M/V] 임창정 - 힘든 건 사랑이 아니다 (IM CHANG JUNG - Love should not be harsh on you)\n\n임창정 정규 16집 타이틀 곡 "힘든 건 사랑이 아니다"는 ‘임창정 16집 타이틀 선정단’의 직접 투표를 통한 압도적인 지지로 선정되었으며 임창정 본인이 재녹음을 수없이 할 만큼 애착을 갖고 탄생시킨 곡이다. 타이틀 선정단이 노래를 듣자마자 눈물을 흘릴 만큼 애절하고 가슴 아픈 사랑 이야기를 담고 있으며 "또다시 사랑" "내가 저지른 사랑" "하루도 그대를 사랑한 적이 없었다" 이후 귓가에 꽂히게 하는 중독성 강한 곡이다. 빗소리와 함께 피아노로 시작하는 전주는 리스너들로 하여금 감성에 빠져들게 하며 임창정의 독보적인 고음으로 빚어낸 후렴의 절정은 사랑하는 사람을 떠나보낼 수밖에 없는 슬픔을 극대화한다. 오랜 시간 함께 해온 히트 메이커 콤비 ‘임창정’과 ‘멧돼지’, 그리고 신예 프로듀서 ‘늑대’ 가 함께 만들어 낸 또 다른 역작으로, 국내 최고의 세션들이 참여해 최고의 퀄리티를 만들어 냈다.',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'vPDlnNJfBTloHG8kl8-a6GSaem0',
      id: 'wyNwbYl1fQk',
      snippet: {
        publishedAt: '2020-10-19T09:12:28Z',
        channelId: 'UCF5gnykb86dwedwxvsRICXg',
        title: '힘든 건 사랑이 아니다 (Love should not be harsh on you)',
        description:
          'Provided to YouTube by Interpark Corp\n\n힘든 건 사랑이 아니다 (Love should not be harsh on you) · 임창정 (IM CHANG JUNG)\n\n힘든 건 사랑이 아니다 (Love should not be harsh on you)\n\n℗ 2020 Interpark\n\nReleased on: 2020-10-19\n\nAuto-generated by YouTube.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/wyNwbYl1fQk/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/wyNwbYl1fQk/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/wyNwbYl1fQk/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/wyNwbYl1fQk/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/wyNwbYl1fQk/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Im Chang-jung - Topic',
        tags: [
          '임창정 (IM CHANG JUNG)',
          '힘든 건 사랑이 아니다 (Love should not be harsh on you)',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        localized: {
          title: '힘든 건 사랑이 아니다 (Love should not be harsh on you)',
          description:
            'Provided to YouTube by Interpark Corp\n\n힘든 건 사랑이 아니다 (Love should not be harsh on you) · 임창정 (IM CHANG JUNG)\n\n힘든 건 사랑이 아니다 (Love should not be harsh on you)\n\n℗ 2020 Interpark\n\nReleased on: 2020-10-19\n\nAuto-generated by YouTube.',
        },
      },
    },
    {
      kind: 'youtube#video',
      etag: 'uyKxoRQZPaC7E1J01FVXiirV6zY',
      id: 'xaoQgpvoZz8',
      snippet: {
        publishedAt: '2020-10-18T00:00:12Z',
        channelId: 'UC271vX3c3kYZsgpz7-zPBoA',
        title:
          '[나는 남자다 #9] 진짜 모시기힘든 분들 어렵게~! 모두 모셨습니다!! 숨겨진 유재석 가족들 다 나왔네 ㅋㅋㅋㅋ',
        description:
          '#나는남자다 #하이라이트 #레전드순삭\n[나는 남자다 하이라이트]\n\n방송일 : 2014년 10월 03일\n게스트: 김태우, 이국주\n\n- 중간 중간 계속 잡히는 유재석1~8 볼 때 마다 진짜 깜짝놀라는거 나 뿐이야? ㅋㅋㅋㅋ\n- 솔직히 조인성 콧털 하나라도 닮고 싶은데 저 분 부럽네...\n- 나는 남자다가 이제 해외 유명인들까지 섭외했다...☆\n- 용포에 간디의상까지 준비력 무엇? ㅋㅋㅋ\n\n다시 돌아온 꿀잼, 허니잼 레트로 예능\n깔깔티비, 자매채널 크큭티비\n\n재밌게 보셨다면 구독&좋아요 눌러주세요!\nhttps://www.youtube.com/channel/UC271vX3c3kYZsgpz7-zPBoA',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/xaoQgpvoZz8/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/xaoQgpvoZz8/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/xaoQgpvoZz8/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/xaoQgpvoZz8/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/xaoQgpvoZz8/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'KBS Entertain: 깔깔티비',
        tags: [
          '깔깔',
          'TV',
          'KBS',
          '예능',
          'KBS예능',
          '레전드',
          '레트로',
          '뉴트로',
          '한국방송',
          '레전드순삭',
          '순삭',
          '나는 남자다',
          '유재석',
          '장동민',
          '권오중',
          '토크쇼',
          '허경환',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title:
            '[나는 남자다 #9] 진짜 모시기힘든 분들 어렵게~! 모두 모셨습니다!! 숨겨진 유재석 가족들 다 나왔네 ㅋㅋㅋㅋ',
          description:
            '#나는남자다 #하이라이트 #레전드순삭\n[나는 남자다 하이라이트]\n\n방송일 : 2014년 10월 03일\n게스트: 김태우, 이국주\n\n- 중간 중간 계속 잡히는 유재석1~8 볼 때 마다 진짜 깜짝놀라는거 나 뿐이야? ㅋㅋㅋㅋ\n- 솔직히 조인성 콧털 하나라도 닮고 싶은데 저 분 부럽네...\n- 나는 남자다가 이제 해외 유명인들까지 섭외했다...☆\n- 용포에 간디의상까지 준비력 무엇? ㅋㅋㅋ\n\n다시 돌아온 꿀잼, 허니잼 레트로 예능\n깔깔티비, 자매채널 크큭티비\n\n재밌게 보셨다면 구독&좋아요 눌러주세요!\nhttps://www.youtube.com/channel/UC271vX3c3kYZsgpz7-zPBoA',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'iRC-1Ehh-Vc6YrBDI17pbCMS96w',
      id: 'P2ZMu1eUtYQ',
      snippet: {
        publishedAt: '2020-10-17T12:13:52Z',
        channelId: 'UCOp66Vup07X0YziXaaxqs2A',
        title: '무가 병원에 다녀왔다',
        description:
          '10월8일 무의 상태가 이상하여 병원에 다녀왔습니다.\n복막염이라는 진단을 받았고 치료가 어려울 수 있다는 결과를 들었습니다.\n그리고 일주일 후 재검사를 통해 호전 가능성이 있다는 결과를 다시 받았습니다. \n\n완치 후에 영상으로 알려드리려 했으나 치료가 길어질 것 같고 완치를 장담할 수 없기에 미리 알려드리기로 했습니다. \n무의 상태는 추후에 다시 알려드리겠습니다.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/P2ZMu1eUtYQ/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/P2ZMu1eUtYQ/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/P2ZMu1eUtYQ/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/P2ZMu1eUtYQ/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/P2ZMu1eUtYQ/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'haha ha',
        categoryId: '15',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title: '무가 병원에 다녀왔다',
          description:
            '10월8일 무의 상태가 이상하여 병원에 다녀왔습니다.\n복막염이라는 진단을 받았고 치료가 어려울 수 있다는 결과를 들었습니다.\n그리고 일주일 후 재검사를 통해 호전 가능성이 있다는 결과를 다시 받았습니다. \n\n완치 후에 영상으로 알려드리려 했으나 치료가 길어질 것 같고 완치를 장담할 수 없기에 미리 알려드리기로 했습니다. \n무의 상태는 추후에 다시 알려드리겠습니다.',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'q1VHc3kBqYcGf7Z2gbOCg8g9kNg',
      id: 'LUtnvstYQkk',
      snippet: {
        publishedAt: '2020-10-18T10:54:32Z',
        channelId: 'UCFH9VTXreljLA4KHejcVmVg',
        title: "환불원정대 - Don't touch me (La Chica 시안 demo)",
        description:
          "환불원정대 - Don't touch me (La Chica 시안 demo)\n\n[댄서 리안]\nInstagram : https://www.instagram.com/_rianess\nhttps://www.instagram.com/la.chica_official\nTicktok : https://www.tiktok.com/@dancerian\n\n문의(contact) : itsrian0911@gmail.com\n\n#환불원정대 #DontTouchMe #LaChica #시안 #Demo",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/LUtnvstYQkk/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/LUtnvstYQkk/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/LUtnvstYQkk/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/LUtnvstYQkk/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/LUtnvstYQkk/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '댄서 리안의 JOB다한 일상',
        tags: [
          '청하',
          'Chungha',
          '리안',
          'rian',
          '춤',
          '댄스',
          'dance',
          '안무가',
          'choregraphy',
          '최남미',
          '남미',
          'dancing9',
          '댄싱9',
          '블루아이',
          '레드윙즈',
          'choreographer',
          'Snapping',
          "why don't you know",
          '벌써 12시',
          'gotta go',
          'Roller Coaster',
          '롤러코스터',
          'Chica',
          '청하 라라라',
          '안무가 대상',
          '올해의 안무가',
          'K-hiphop',
          'K-pop',
          '케이팝',
          '환불원정대',
          'La Chica',
          '라치카',
          'Refund sisters',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title: "환불원정대 - Don't touch me (La Chica 시안 demo)",
          description:
            "환불원정대 - Don't touch me (La Chica 시안 demo)\n\n[댄서 리안]\nInstagram : https://www.instagram.com/_rianess\nhttps://www.instagram.com/la.chica_official\nTicktok : https://www.tiktok.com/@dancerian\n\n문의(contact) : itsrian0911@gmail.com\n\n#환불원정대 #DontTouchMe #LaChica #시안 #Demo",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'vTrYc1kR-AkPwlKbPmWirLSJZuA',
      id: 'bvPRAzGfWyo',
      snippet: {
        publishedAt: '2020-10-19T08:33:31Z',
        channelId: 'UCclwLhN5a_ql_9qVvuVOH4A',
        title:
          '임영웅X영탁X이찬원X정동원X장민호X김희재가 직접 뽑은 인생노래 / ‘미스터트롯: 더 무비’ 제작보고회 201019  - 톱데일리(Topdaily)',
        description:
          '✔공정·공익·나눔언론 #톱데일리 \n✔톱데일리 채널 구독하기 https://bit.ly/2LYAnhu\n✔NEVER 뉴스 스탠드에서 톱데일리 뉴스를 만나보세요\n▶https://newsstand.naver.com/826\n\n#영탁 #임영웅 #이찬원 #정동원 #장민호 #김희재 #미스터트롯\n\n톱데일리 최지은 기자 = 19일 오후 코로나19 확산 방지를 위해 온라인에서 진행된 영화 ‘미스터트롯: 더 무비’ 제작보고회에 배우 임영웅, 영탁, 이찬원,정동원, 장민호, 김희재가 참석했다.\n\n영화 ‘미스터트롯: 더 무비’는 내일은 미스터트롯 대국민 감사콘서트’ 서울 공연 실황을 중심으로 방송에서는 다 보여주지 못했던 TOP6의 모든 것을 만나볼 수 있는 찐한 콘서트 무비로 오는 22일 개봉을 앞두고 있다. [영상=미스터트롯: 더 무비]\n\n▶Homepage : http://www.topdaily.kr\n▶Facebook : https://www.facebook.com/topdailymedia/\n▶Twitter : https://twitter.com/TopDaily4\n▶Naver tv : https://tv.naver.com/topdaily\n▶Kakao tv : https://tv.kakao.com/channel/3129404\n--------------------------------------------------------------------------------------------------------------\n톱데일리는 독자분들의 제보를 기다리고 있습니다.\n여러분께서 주신 제보와 취재요청으로 세상을 더욱 가치있게 만들겠습니다. \n\n✔인터뷰요청·뉴스제보·보도자료 E-mail : top@topdaily.co.kr\n--------------------------------------------------------------------------------------------------------------',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/bvPRAzGfWyo/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/bvPRAzGfWyo/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/bvPRAzGfWyo/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/bvPRAzGfWyo/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/bvPRAzGfWyo/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '톱데일리 Top Daily',
        tags: [
          '톱데일리',
          'topdaily',
          '뉴스',
          'news',
          '임영웅',
          '영탁',
          '이찬원',
          '정동원',
          '장민호',
          '김희재',
          '미스터트롯',
          '미스터트롯 더무비 제작보고회',
          '미스터트롯 영화',
          '제작보고회',
          '미스터트롯 임영웅',
          '미스터트롯 영탁',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title:
            '임영웅X영탁X이찬원X정동원X장민호X김희재가 직접 뽑은 인생노래 / ‘미스터트롯: 더 무비’ 제작보고회 201019  - 톱데일리(Topdaily)',
          description:
            '✔공정·공익·나눔언론 #톱데일리 \n✔톱데일리 채널 구독하기 https://bit.ly/2LYAnhu\n✔NEVER 뉴스 스탠드에서 톱데일리 뉴스를 만나보세요\n▶https://newsstand.naver.com/826\n\n#영탁 #임영웅 #이찬원 #정동원 #장민호 #김희재 #미스터트롯\n\n톱데일리 최지은 기자 = 19일 오후 코로나19 확산 방지를 위해 온라인에서 진행된 영화 ‘미스터트롯: 더 무비’ 제작보고회에 배우 임영웅, 영탁, 이찬원,정동원, 장민호, 김희재가 참석했다.\n\n영화 ‘미스터트롯: 더 무비’는 내일은 미스터트롯 대국민 감사콘서트’ 서울 공연 실황을 중심으로 방송에서는 다 보여주지 못했던 TOP6의 모든 것을 만나볼 수 있는 찐한 콘서트 무비로 오는 22일 개봉을 앞두고 있다. [영상=미스터트롯: 더 무비]\n\n▶Homepage : http://www.topdaily.kr\n▶Facebook : https://www.facebook.com/topdailymedia/\n▶Twitter : https://twitter.com/TopDaily4\n▶Naver tv : https://tv.naver.com/topdaily\n▶Kakao tv : https://tv.kakao.com/channel/3129404\n--------------------------------------------------------------------------------------------------------------\n톱데일리는 독자분들의 제보를 기다리고 있습니다.\n여러분께서 주신 제보와 취재요청으로 세상을 더욱 가치있게 만들겠습니다. \n\n✔인터뷰요청·뉴스제보·보도자료 E-mail : top@topdaily.co.kr\n--------------------------------------------------------------------------------------------------------------',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'cWewrxb5PtGl4SVUtN_C7UVYI0E',
      id: '4hZcm6-XZ0Q',
      snippet: {
        publishedAt: '2020-10-19T05:00:00Z',
        channelId: 'UCtm_QoN2SIxwCE-59shX7Qg',
        title: '[20/21 PL 5R] 토트넘 vs 웨스트햄 H/L',
        description: '5R 토트넘 vs 웨스트햄 경기 하이라이트',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/4hZcm6-XZ0Q/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/4hZcm6-XZ0Q/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/4hZcm6-XZ0Q/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/4hZcm6-XZ0Q/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/4hZcm6-XZ0Q/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'SPOTV',
        tags: [
          'SPOTV',
          '스포티비',
          '토트넘',
          '웨스트햄',
          '해리케인',
          '손흥민',
          '가레스 베일',
          '베일',
          '발부에나',
          '란시니',
          '산체스',
          '무리뉴',
          '모예스',
        ],
        categoryId: '17',
        liveBroadcastContent: 'none',
        localized: {
          title: '[20/21 PL 5R] 토트넘 vs 웨스트햄 H/L',
          description: '5R 토트넘 vs 웨스트햄 경기 하이라이트',
        },
      },
    },
    {
      kind: 'youtube#video',
      etag: '8UT18cNiadbmkTguik_pCCGYT4k',
      id: 'gBnEJXvACP0',
      snippet: {
        publishedAt: '2020-10-18T15:00:09Z',
        channelId: 'UCuhAUMLzJxlP1W7mEk0_6lA',
        title: '[TEASER] 마마무 (MAMAMOO) - 딩가딩가 (Dingga)',
        description:
          "[TEASER] 마마무 (MAMAMOO) - 딩가딩가 (Dingga)\n\r\nInstagram: https://bit.ly/2TrQPJD\r\nFacebook: https://bit.ly/2OYoA1W\r\nTwitter: https://bit.ly/2TuKNbo\r\n\r\nAbout MAMAMOO.\r\nMAMAMOO(마마무) OFFICIAL CHANNEL\r\n\r\n#MAMAMOO #마마무 #딩가딩가\r\n\r\nMAMAMOO.\r\nSUBSCRIBE: https://bit.ly/2PFdfsI\r\nhttps://www.youtube.com/c/MAMAMOO_OFFICIAL\r\n\r\nDon't forget to subscribe, like and leave a comment.",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/gBnEJXvACP0/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/gBnEJXvACP0/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/gBnEJXvACP0/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/gBnEJXvACP0/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/gBnEJXvACP0/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'MAMAMOO',
        tags: [
          'MAMAMOO',
          '마마무',
          '딩가딩가',
          'Dingga',
          '마마무 딩가딩가',
          '마마무 Dingga',
          'MAMAMOO Dingga',
          '딩가딩가 티저',
          'Dingga Teaser',
          '마마무 딩가딩가 티저',
          '딩가딩가 뮤비 티저',
          '마마무 티저',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title: '[TEASER] 마마무 (MAMAMOO) - 딩가딩가 (Dingga)',
          description:
            "[TEASER] 마마무 (MAMAMOO) - 딩가딩가 (Dingga)\n\r\nInstagram: https://bit.ly/2TrQPJD\r\nFacebook: https://bit.ly/2OYoA1W\r\nTwitter: https://bit.ly/2TuKNbo\r\n\r\nAbout MAMAMOO.\r\nMAMAMOO(마마무) OFFICIAL CHANNEL\r\n\r\n#MAMAMOO #마마무 #딩가딩가\r\n\r\nMAMAMOO.\r\nSUBSCRIBE: https://bit.ly/2PFdfsI\r\nhttps://www.youtube.com/c/MAMAMOO_OFFICIAL\r\n\r\nDon't forget to subscribe, like and leave a comment.",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'iEEcT3mHw1ja0J2wFmthj80ZG-E',
      id: '01iz9kmvbxg',
      snippet: {
        publishedAt: '2020-10-17T00:43:37Z',
        channelId: 'UCOHM2N1YQdb-cHWxJxwBMLQ',
        title:
          "[ENG│선공개] 리사(LISA)의 ⚡️업그레이드된 태국 춤 = '게 춤'♪ (point. 무표정😶) 아는 형님(Knowing bros) 251회",
        description:
          "[선공개] 리사의 ⚡️업그레이드된 태국 춤 = '게 춤'♪ (point. 무표정😶)\n#아는형님 #블랙핑크 #리사",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/01iz9kmvbxg/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/01iz9kmvbxg/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/01iz9kmvbxg/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/01iz9kmvbxg/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/01iz9kmvbxg/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '아는형님 Knowingbros',
        tags: [
          '아는 형님',
          '형님',
          '형님 학교',
          '블랙핑크',
          '제니',
          '지수',
          '로제',
          '리사',
          '선공개',
          '태국춤',
          '게춤',
          '업그레이드',
          '댄스',
          '춤',
          '댄스수업',
          'BLACKPINK',
          'JISOO',
          'JENNIE',
          'ROS&Eacute;',
          'LISA',
          '예능',
          '슈퍼주니어',
          '버즈',
          'Knowing bros',
          'Knowing brother',
          'min kyung hoon',
          'kim hee chul',
          'kang ho dong',
          'seo jang hoon',
          'lee soo geun',
          'kim young chul',
          'lee sang min',
          'buzz',
          'superjunior',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'ko',
        localized: {
          title:
            "[ENG│선공개] 리사(LISA)의 ⚡️업그레이드된 태국 춤 = '게 춤'♪ (point. 무표정😶) 아는 형님(Knowing bros) 251회",
          description:
            "[선공개] 리사의 ⚡️업그레이드된 태국 춤 = '게 춤'♪ (point. 무표정😶)\n#아는형님 #블랙핑크 #리사",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'c1WqQcVgJUezqAkM-lACmyH6eLQ',
      id: 'z8tHmk_Ralk',
      snippet: {
        publishedAt: '2020-10-17T11:00:11Z',
        channelId: 'UCIUfR-2qcpWqgAIfZJXOLWA',
        title: '국산연어 먹다 고래회충까지 먹었는데 저 어떡하죠? Anisakis',
        description:
          '국산연어(자연산) 구매처 : 황실푸드\n오비라거 구매처 : 이마트\n\n\n*수산물의 시세는 매일 달라질 수 있습니다.\n*광고 또는 협찬 표시가 없을 시 직접 사비구매한 상품입니다.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/z8tHmk_Ralk/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/z8tHmk_Ralk/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/z8tHmk_Ralk/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/z8tHmk_Ralk/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/z8tHmk_Ralk/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: '수빙수tv sooBingsoo',
        tags: [
          '국산연어',
          '노르웨이연어',
          '자연산연어',
          '양식연어',
          '연어회',
          '연어초밥',
          'salmon',
        ],
        categoryId: '22',
        liveBroadcastContent: 'none',
        localized: {
          title: '국산연어 먹다 고래회충까지 먹었는데 저 어떡하죠? Anisakis',
          description:
            '국산연어(자연산) 구매처 : 황실푸드\n오비라거 구매처 : 이마트\n\n\n*수산물의 시세는 매일 달라질 수 있습니다.\n*광고 또는 협찬 표시가 없을 시 직접 사비구매한 상품입니다.',
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'SQfzpMgxYQ4Ym438cKOY0-7Dzk4',
      id: '3p7s7Rjh4fg',
      snippet: {
        publishedAt: '2020-10-19T09:00:15Z',
        channelId: 'UCEf_Bc-KVd7onSeifS3py9g',
        title: "NCT U 엔시티 유 'From Home' MV",
        description:
          "NCT's 2nd album \"NCT - The 2nd Album RESONANCE Pt. 1\" is out!\n🎧Listen and download on your favorite platform: https://nct2020.lnk.to/resonanceID\n🎁Official store: https://nct2020official.com\n\n[Tracklist]\n01 Make A Wish (Birthday Song)\n02 Misfit\n03 Volcano\n04 백열등 (Light Bulb)\n05 Dancing In The Rain\n06 Interlude : Past to Present\n07 무대로 (déjà vu; 舞代路)\n08 月之迷 (Nectar)\n09 Music, Dance\n10 피아노 (Faded In My Last Song)\n11 From Home\n12 From Home (Korean Ver.)\n13 Make A Wish (Birthday Song) (English Ver.)\n\nNCT Official\nhttp://www.nct2020.com\nhttp://www.youtube.com/nctsmtown\nhttp://www.facebook.com/NCT.smtown\nhttp://www.instagram.com/nct\nhttp://twitter.com/NCTsmtown\n\n#NCT #RESONANCE #FromHome #RESONANCE_Pt1\nNCT U 엔시티 유 'From Home' MV ℗ SM Entertainment",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/3p7s7Rjh4fg/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/3p7s7Rjh4fg/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/3p7s7Rjh4fg/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/3p7s7Rjh4fg/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/3p7s7Rjh4fg/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'SMTOWN',
        categoryId: '10',
        liveBroadcastContent: 'none',
        localized: {
          title: "NCT U 엔시티 유 'From Home' MV",
          description:
            "NCT's 2nd album \"NCT - The 2nd Album RESONANCE Pt. 1\" is out!\n🎧Listen and download on your favorite platform: https://nct2020.lnk.to/resonanceID\n🎁Official store: https://nct2020official.com\n\n[Tracklist]\n01 Make A Wish (Birthday Song)\n02 Misfit\n03 Volcano\n04 백열등 (Light Bulb)\n05 Dancing In The Rain\n06 Interlude : Past to Present\n07 무대로 (déjà vu; 舞代路)\n08 月之迷 (Nectar)\n09 Music, Dance\n10 피아노 (Faded In My Last Song)\n11 From Home\n12 From Home (Korean Ver.)\n13 Make A Wish (Birthday Song) (English Ver.)\n\nNCT Official\nhttp://www.nct2020.com\nhttp://www.youtube.com/nctsmtown\nhttp://www.facebook.com/NCT.smtown\nhttp://www.instagram.com/nct\nhttp://twitter.com/NCTsmtown\n\n#NCT #RESONANCE #FromHome #RESONANCE_Pt1\nNCT U 엔시티 유 'From Home' MV ℗ SM Entertainment",
        },
        defaultAudioLanguage: 'ko',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'LHooYh0egyNt_RrcNuEmBKyDHNc',
      id: 'F4qugKTiiK8',
      snippet: {
        publishedAt: '2020-10-18T09:38:38Z',
        channelId: 'UCIcXK1CI8URMIqNO_1cehiQ',
        title: 'LEE SUHYUN - ‘ALIEN’ 1018 SBS Inkigayo',
        description:
          'Copyrightⓒ2020 SBS Contents Hub Co., Ltd. & YG Entertainment Inc. All rights reserved.\n\n[LEE SUHYUN - ‘ALIEN’ 1018 SBS Inkigayo]\n\n*NAVER TV로 보기 : https://tv.naver.com/v/16277330 \n\n#LEESUHYUN #이수현 #ALIEN \n\nMore about AKMU @\nhttp://www.yg-akmu.com/\nhttp://www.youtube.com/officialAKMU\nhttps://www.facebook.com/officialAKMU\nhttp://twitter.com/ygent_official',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/F4qugKTiiK8/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/F4qugKTiiK8/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/F4qugKTiiK8/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/F4qugKTiiK8/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/F4qugKTiiK8/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'AKMU',
        tags: [
          'YG Entertainment',
          'YG',
          '와이지',
          'K-pop',
          '악동뮤지션',
          '악뮤',
          'AKDONG MUSICIAN',
          'AKMU',
          '이찬혁',
          '이수현',
          'Lee Chanhyuk',
          'Lee Suhyun',
          '찬혁',
          '수현',
          'Chanhyuk',
          'Suhyun',
          'ALIEN',
          'LEE SUHYUN ALIEN',
          '수현 ALIEN',
          '이수현 ALIEN',
          '인기가요',
          'Inkigayo',
          '이수현 인기가요',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        localized: {
          title: 'LEE SUHYUN - ‘ALIEN’ 1018 SBS Inkigayo',
          description:
            'Copyrightⓒ2020 SBS Contents Hub Co., Ltd. & YG Entertainment Inc. All rights reserved.\n\n[LEE SUHYUN - ‘ALIEN’ 1018 SBS Inkigayo]\n\n*NAVER TV로 보기 : https://tv.naver.com/v/16277330 \n\n#LEESUHYUN #이수현 #ALIEN \n\nMore about AKMU @\nhttp://www.yg-akmu.com/\nhttp://www.youtube.com/officialAKMU\nhttps://www.facebook.com/officialAKMU\nhttp://twitter.com/ygent_official',
        },
        defaultAudioLanguage: 'ko',
      },
    },
  ],
  nextPageToken: 'CBkQAA',
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 25,
  },
};
